operation = input('Type in the operator you want (eg. divide = /, multiply = *, etc.): ')
a = input('Type in tour first number: ')
b = input('Type in your second number: ') 
c = str(a), operation, str(b)
print (c)
