from time import sleep
print('Hi there.')
sleep(1.5)
print('Today,')
sleep(1)
print('I will show you')
sleep(1)
print('that anything can equal the Illuminati.')
sleep(3)
print('Before we begin,')
sleep(1)
print('please get a food processor')
sleep(1.5)
print('because we are about to grind some sh*t up.')
sleep(1.5)
illuminati_phrase = raw_input('Now, type in something because I don\'t f*cking care: ')
illuminati_len = int(len(illuminati_phrase))
def illuminati_thing():
	print(illuminati_phrase + 'has ' + int(illuminati_len) + 'letters.')
illuminati_thing()
 
