from time import sleep
import random 
print ("Welcome to Jack Potts Lottery!")
sleep(1.5)
print ("Behind 1 virtual door is the chance to say, 'I survived Jack Potts Lottery!' to your friends!")
sleep(2)
print ("Behind the other is the dreaded island of 'Happyland!'")
sleep(2)
player_answer = input("So, what will it be? 1 or 2? ")
real_answer = random.randint(1, 2) 
while int(player_answer) not in range(1, 3):
    player_answer = input("No, no, you have to pick, 1 or 2? ")
print ("Importing pick...")
sleep(5)
print ("Decoding pick...")
sleep(6)
print ("Recalling algorithms...")
sleep(4)
print ("Calculating probability algorithms...")
sleep(7)
print ("Solving probability algorithms...")
sleep(6)
print ("Double-checking answer...")
sleep(4)
print ("Downloading rewards...")
sleep(4)
print ("Exporting answer...")
sleep(3)
if player_answer != str(real_answer):     
	print ("Your picked door was: " + str(player_answer))
	sleep(1)
	print ("The computer-generated pick was: " + str(real_answer))
	sleep(1)
	print ("Oops, better luck next time! But you win a world full of beautiful flowers and frogs and trolls and all the things you would find in Happyland!")
if player_answer == str(real_answer):
	print ("Your picked door was: " + str(player_answer))
	sleep(1)
	print ("The computer-generated pick was: " + str(real_answer))
	sleep(1)
	print ("Aww, I hate it when I lose! You can go and say you survived my lottery!")
